apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-resource
  namespace: default
spec:
  replicas: 2
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
